// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMapsearch = "mapsearch"

// Mapsearch mapped from table <mapsearch>
type Mapsearch struct {
	ID        string   `gorm:"column:id;type:character varying(20);primaryKey" json:"id"`
	Name      string   `gorm:"column:name;type:character varying(180);not null" json:"name"`
	State     string   `gorm:"column:state;type:character varying(20);not null" json:"state"`
	County    *string  `gorm:"column:county;type:character varying(180)" json:"county"`
	Centroid  Geometry `gorm:"column:centroid;type:geometry(Point,4326);not null;index:mapsearch_centroid_idx,priority:1" json:"centroid"`
	StateName string   `gorm:"column:state_name;type:character varying(180);not null" json:"state_name"`
}

// TableName Mapsearch's table name
func (*Mapsearch) TableName() string {
	return TableNameMapsearch
}
