// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSavedArea = "saved_areas"

// SavedArea mapped from table <saved_areas>
type SavedArea struct {
	ID              string    `gorm:"column:id;type:character(12);primaryKey" json:"id"`
	PassedZones     string    `gorm:"column:passed_zones;type:text;not null" json:"passed_zones"`
	Border          *Geometry `gorm:"column:border;type:geometry(Geometry,4326);index:saved_geo_idx,priority:1" json:"border"`
	CalculatedZones string    `gorm:"column:calculated_zones;type:text;not null" json:"calculated_zones"`
}

// TableName SavedArea's table name
func (*SavedArea) TableName() string {
	return TableNameSavedArea
}
