// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZone = "zones"

// Zone mapped from table <zones>
type Zone struct {
	ID     string   `gorm:"column:id;type:text;primaryKey" json:"id"`
	Name   string   `gorm:"column:name;type:text;not null" json:"name"`
	Type   string   `gorm:"column:type;type:text;not null" json:"type"`
	State  *string  `gorm:"column:state;type:text;default:XX" json:"state"`
	Border Geometry `gorm:"column:border;type:geometry(Geometry,4326);not null;index:zone_border_geo_idx,priority:1" json:"border"`
}

// TableName Zone's table name
func (*Zone) TableName() string {
	return TableNameZone
}
